### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by smallnine9** [indeedeng/lsmtree#9]

**Comment by smallnine9** [comment]
I am sorry to ask a so naive question, I am  a student and I want to study LSM, but I am not familiar with java project, so I want to know how run this code

**Comment by youknowjack** [comment]
We do not have a good Getting Started guide at this time.  To be honest, this is a pretty difficult codebase to run, even for those familiar with Java. It has some native code dependencies and probably only works in certain environments (linux) and Java versions (Oracle JDK 8). There be monsters here, I'd advise steering into better charted waters. Sorry.
